config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :categories
      resources :products
      resources :users

      root to: "categories#index"
    end
  resources :categories, only: %i(index show)
  devise_for :users
  patch "/cart", to: "carts#update", as: :add_to_cart
  get "/checkout", to: "checkouts#show", as: :checkout
  get "/stripe-checkout", to: "stripe_checkouts#new", as: :stripe_checkout
  get "/stripe-checkout-handler", to: "stripe_checkout_handlers#show", as: :stripe_checkout_handler
  get "up" => "rails/health#show", as: :rails_health_check

  root "site#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :line_items, dependent: :destroy

  def add_item(product_id, quantity)
    current_item = LineItem.find_by(product_id: product_id, cart: self)
    product = Product.find(product_id)
    if current_item
      qty = quantity || current_item.quantity + 1
      current_item.update(quantity: qty)
    else
      current_item = LineItem.create!(
        product_id: product.id,
        quantity: quantity,
        cart: self,
        price: product.price
      )
    end
    current_item
  end

  def total
    line_items.sum { |i| i.price * i.quantity }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def update
    @cart = current_user.cart

    @cart.add_item(params[:product_id], params[:quantity])

    if @cart.save
      flash[:notice] = "Product added to cart"
      render turbo_stream: [
        turbo_stream.replace(@cart),
        turbo_stream.update("checkout-subtotal", @cart.total),
        turbo_stream.replace("flash", partial: "shared/flashes")
      ]
    else
      flash[:alert] = "Cannot add product to cart"
      render turbo_stream: [
        turbo_stream.replace("flash", partial: "shared/flashes")
      ]
    end
  end
end

app/views/carts/_cart.html.erb
<div class="ml-4 flow-root lg:ml-8" id="<%= dom_id(current_user.cart) %>">
  <%= link_to checkout_path, class: "group -m-2 flex items-center p-2" do %>
    <svg class="h-6 w-6 flex-shrink-0 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
    </svg>
    <span class="ml-2 text-sm font-medium text-white"><%= current_user.cart.line_items.count %></span>
    <span class="sr-only">items in cart, view bag</span>
  <% end %>
</div>