config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :categories
      resources :products
      resources :users

      root to: "categories#index"
    end
  resources :categories, only: %i(index show)
  devise_for :users
  patch "/cart", to: "carts#update", as: :add_to_cart
  get "/checkout", to: "checkouts#show", as: :checkout
  get "/stripe-checkout", to: "stripe_checkouts#new", as: :stripe_checkout
  get "/stripe-checkout-handler", to: "stripe_checkout_handlers#show", as: :stripe_checkout_handler
  get "up" => "rails/health#show", as: :rails_health_check

  root "site#index"
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def show
    @cart = current_user.cart
  end
end

app/views/checkouts/show.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 pb-24 pt-16 sm:px-6 lg:max-w-7xl lg:px-8">
    <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Checkout</h1>
    <section aria-labelledby="cart-heading" class="lg:col-span-7">
      <h2 id="cart-heading" class="sr-only">Items in your shopping cart</h2>

      <ul role="list" class="divide-y divide-gray-200 border-b border-t border-gray-200">
        <% @cart.line_items.each do |item| %>
        <li class="flex py-6 sm:py-10">
          <div class="flex-shrink-0">
            <% if item.product.images.attached? %>
              <%= image_tag item.product.images.first, class: "h-24 w-24 rounded-md object-cover object-center sm:h-48 sm:w-48" %>
            <% else %>
              <%= image_tag "https://placehold.co/600x400", class: "h-24 w-24 rounded-md object-cover object-center sm:h-48 sm:w-48" %>
            <% end %>
          </div>

          <div class="ml-4 flex flex-1 flex-col justify-between sm:ml-6">
            <div class="relative pr-9 sm:grid sm:grid-cols-2 sm:gap-x-6 sm:pr-0">
              <div>
                <div class="flex justify-between">
                  <h3 class="text-sm">
                    <%= link_to item.product.name, class: "font-medium text-gray-700 hover:text-gray-800" %>
                  </h3>
                </div>
                <p class="mt-1 text-sm font-medium text-gray-900"><%= number_to_currency item.product.price %></p>
              </div>

              <div class="mt-4 sm:mt-0 sm:pr-9">
                <label for="quantity" class="sr-only">Quantity</label>
                <%= form_with model: item, url: add_to_cart_path(product_id: item.product.id), data: { controller: "carts" }, scope: "" do |f| %>
                  <%= f.select :quantity, 1..8, {}, class: "max-w-full rounded-md border border-gray-300 py-1.5 text-left text-base font-medium leading-5 text-gray-700 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 sm:text-sm", data: { action: "change->carts#select" } %>
                <% end %>

                <div class="absolute right-0 top-0">
                  <button type="button" class="-m-2 inline-flex p-2 text-gray-400 hover:text-gray-500">
                    <span class="sr-only">Remove</span>
                    <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>

            <p class="mt-4 flex space-x-2 text-sm text-gray-700">
              <svg class="h-5 w-5 flex-shrink-0 text-green-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 01.143 1.052l-8 10.5a.75.75 0 01-1.127.075l-4.5-4.5a.75.75 0 011.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 011.05-.143z" clip-rule="evenodd" />
              </svg>
              <span>In stock</span>
            </p>
          </div>
        </li>
      <% end %>
      </ul>
    </section>

    <!-- Order summary -->
    <section aria-labelledby="summary-heading" class="mt-16 rounded-lg bg-gray-50 px-4 py-6 sm:p-6 lg:col-span-5 lg:mt-0 lg:p-8">
      <h2 id="summary-heading" class="text-lg font-medium text-gray-900">Order summary</h2>

      <dl class="mt-6 space-y-4">
        <div class="flex items-center justify-between border-t border-gray-200 pt-4">
          <dt class="text-base font-medium text-gray-900">Order subtotal</dt>
          <dd class="text-base font-medium text-gray-900" id="checkout-subtotal"><%= @cart.total %></dd>
        </div>
      </dl>

      <div class="mt-6">
        <%= link_to "Checkout", stripe_checkout_path, class: "w-full rounded-md border border-transparent bg-indigo-600 px-4 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50" %>
      </div>
    </section>
  </div>
</div>