config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :categories
      resources :products
      resources :users

      root to: "categories#index"
    end
  resources :categories, only: %i(index show)
  devise_for :users
  patch "/cart", to: "carts#update", as: :add_to_cart
  get "/checkout", to: "checkouts#show", as: :checkout
  get "/stripe-checkout", to: "stripe_checkouts#new", as: :stripe_checkout
  get "/stripe-checkout-handler", to: "stripe_checkout_handlers#show", as: :stripe_checkout_handler
  get "up" => "rails/health#show", as: :rails_health_check

  root "site#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
  validates :description, presence: true
  has_one_attached :image
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<main>
  <section aria-labelledby="category-heading" class="pt-24 sm:pt-32 xl:mx-auto xl:max-w-7xl xl:px-8">
    <div class="px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0">
      <h2 id="category-heading" class="text-2xl font-bold tracking-tight text-gray-900">Shop by Category</h2>
    </div>

    <div class="mt-4 flow-root">
      <div class="-my-2">
        <div class="relative box-content h-80 overflow-x-auto py-2 xl:overflow-visible">
          <div class="absolute flex space-x-8 px-4 sm:px-6 lg:px-8 xl:relative xl:grid xl:grid-cols-5 xl:gap-x-8 xl:space-x-0 xl:px-0">
            <% @categories.each do |category| %>
              <%= link_to category_path(category), class: "relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto" do %>
                <span aria-hidden="true" class="absolute inset-0">
                  <% if category.image.attached? %>
                    <%= image_tag category.image, class: "h-full w-full object-cover object-center" %>
                  <% else %>
                    <img src="https://tailwindui.com/img/ecommerce-images/home-page-01-category-01.jpg" alt="" class="h-full w-full object-cover object-center">
                  <% end %>
                </span>
                <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
                <span class="relative mt-auto text-center text-xl font-bold text-white"><%= category.name %></span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/categories/show.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <div class="md:items-center md:justify-between">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900"><%= @category.name %></h2>
      <% if @category.description.present? %>
        <p class="block"><%= @category.description %></p>
      <% end %>
    </div>

    <div class="mt-6 grid grid-cols-2 gap-x-4 gap-y-10 sm:gap-x-6 md:grid-cols-4 md:gap-y-0 lg:gap-x-8">
      <% @category.products.each do |product| %>
      <div class="group relative">
        <div class="h-56 w-full overflow-hidden rounded-md bg-gray-200 lg:h-72 xl:h-80">
          <% if product.images.attached? %>
            <%= image_tag product.images.first, class: "h-full w-full object-cover object-center" %>
          <% end %>
        </div>
        <div class="flex justify-between mt-2">
          <div>
            <p class="mt-1 text-sm text-gray-500"><%= product.name %></p>
            <p class="mt-1 text-sm font-medium text-gray-900">$75</p>
          </div>
          <%= button_to "Add to Cart", add_to_cart_path(product_id: product.id), method: :patch, class: "rounded-md border border-transparent bg-gray-100 px-8 py-2 text-sm font-medium text-gray-900 hover:bg-gray-200" %>
        </div>
        <h3 class="mt-4 text-sm text-gray-700">
          <%= product.description %>
        </h3>
      </div>
      <% end %>

      <!-- More products... -->
    </div>

    <div class="mt-8 text-sm md:hidden">
      <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
        Shop the collection
        <span aria-hidden="true"> &rarr;</span>
      </a>
    </div>
  </div>
</div>